"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { CalendarDays, Check, ChevronDown, ChevronLeft, ChevronRight, CirclePlus, Database, Download, GripVertical, History, ImagePlus, Minus, Mountain, Plus, RotateCcw, Sparkles, Star, Trash2, Upload, X } from "lucide-react";
import { Checkbox } from "@/components/ui/checkbox";
import { Progress } from "@/components/ui/progress";

type Review = { effort: number; achievement: number; note: string; image?: string };
type Stone = { id: string; action: string; weight: number; outcome: string; done: boolean; review: Review; starterAction: string };
type BigStone = { id: string; title: string; finishLine: string; stones: Stone[]; completedAt?: string };
type DayData = { bigStones: BigStone[]; freeStones: Stone[] };
type Unlocks = { completedBigStoneIds: string[]; twoStoneDays: string[]; second: boolean; third: boolean };
type AppData = { version: 2; days: Record<string, DayData>; unlocks: Unlocks; lastExportAt?: string };
type View = "today" | "history" | "data";
type Celebration = { kind: "small" | "big" | "second" | "third"; weight: number };

const STORAGE_KEY = "move-one-stone-v02";
const LEGACY_KEY = "shitouji-v01-days";
const uid = () => typeof crypto !== "undefined" && "randomUUID" in crypto ? crypto.randomUUID() : `${Date.now()}-${Math.random()}`;
const blankReview = (): Review => ({ effort: 0, achievement: 0, note: "" });
const newStone = (overrides: Partial<Stone> = {}): Stone => ({ id: uid(), action: "", weight: 1, outcome: "", done: false, review: blankReview(), starterAction: "", ...overrides });
const newBigStone = (): BigStone => ({ id: uid(), title: "", finishLine: "", stones: [newStone()] });
const emptyDay = (): DayData => ({ bigStones: [newBigStone()], freeStones: [] });
const emptyData = (): AppData => ({ version: 2, days: {}, unlocks: { completedBigStoneIds: [], twoStoneDays: [], second: false, third: false } });
const dateKey = (date: Date) => `${date.getFullYear()}-${`${date.getMonth() + 1}`.padStart(2, "0")}-${`${date.getDate()}`.padStart(2, "0")}`;
const todayKey = () => dateKey(new Date());
const displayDate = (value: string) => { const date = new Date(`${value}T12:00:00`); const yesterday = new Date(); yesterday.setDate(yesterday.getDate() - 1); const prefix = value === todayKey() ? "今天" : value === dateKey(yesterday) ? "昨天" : ""; return `${prefix ? `${prefix} · ` : ""}${date.getMonth() + 1}月${date.getDate()}日 周${"日一二三四五六"[date.getDay()]}`; };
const shiftDate = (value: string, amount: number) => { const date = new Date(`${value}T12:00:00`); date.setDate(date.getDate() + amount); return dateKey(date); };
const isBigStoneComplete = (stone: BigStone) => Boolean(stone.title.trim() && stone.stones.length && stone.stones.every((item) => item.action.trim() && item.done));
const allowedBigStones = (unlocks: Unlocks) => unlocks.third ? 3 : unlocks.second ? 2 : 1;
const unique = <T,>(items: T[]) => [...new Set(items)];

const normalizeReview = (value: Partial<Review> | undefined): Review => ({ effort: Number(value?.effort) || 0, achievement: Number(value?.achievement) || 0, note: typeof value?.note === "string" ? value.note : "", image: typeof value?.image === "string" ? value.image : undefined });
const normalizeStone = (value: Partial<Stone> | undefined): Stone => ({ id: typeof value?.id === "string" ? value.id : uid(), action: typeof value?.action === "string" ? value.action : "", weight: Math.min(5, Math.max(1, Number(value?.weight) || 1)), outcome: typeof value?.outcome === "string" ? value.outcome : "", done: Boolean(value?.done), review: normalizeReview(value?.review), starterAction: typeof value?.starterAction === "string" ? value.starterAction : "" });
const normalizeBigStone = (value: Partial<BigStone> | undefined): BigStone => ({ id: typeof value?.id === "string" ? value.id : uid(), title: typeof value?.title === "string" ? value.title : "", finishLine: typeof value?.finishLine === "string" ? value.finishLine : "", stones: Array.isArray(value?.stones) && value.stones.length ? value.stones.map(normalizeStone) : [newStone()], completedAt: typeof value?.completedAt === "string" ? value.completedAt : undefined });

function normalizeData(raw: unknown): AppData {
  if (!raw || typeof raw !== "object") throw new Error("invalid backup");
  const candidate = raw as Partial<AppData> & { days?: Record<string, unknown> };
  if (candidate.version === 2 && candidate.days && typeof candidate.days === "object") {
    const days = Object.fromEntries(Object.entries(candidate.days).map(([key, value]) => { const day = value as Partial<DayData>; return [key, { bigStones: Array.isArray(day.bigStones) && day.bigStones.length ? day.bigStones.map(normalizeBigStone) : [newBigStone()], freeStones: Array.isArray(day.freeStones) ? day.freeStones.map(normalizeStone) : [] }]; }));
    const unlocks = candidate.unlocks;
    return { version: 2, days, unlocks: { completedBigStoneIds: Array.isArray(unlocks?.completedBigStoneIds) ? unlocks.completedBigStoneIds.filter((id): id is string => typeof id === "string") : [], twoStoneDays: Array.isArray(unlocks?.twoStoneDays) ? unlocks.twoStoneDays.filter((id): id is string => typeof id === "string") : [], second: Boolean(unlocks?.second), third: Boolean(unlocks?.third) }, lastExportAt: typeof candidate.lastExportAt === "string" ? candidate.lastExportAt : undefined };
  }
  const legacyDays = candidate.days ?? raw as Record<string, unknown>; const completedBigStoneIds: string[] = [];
  const days = Object.fromEntries(Object.entries(legacyDays).map(([key, value]) => { const old = value as { bigStone?: unknown; finishLine?: unknown; stones?: unknown; freeStones?: unknown; starterAction?: unknown }; const stones = Array.isArray(old.stones) && old.stones.length ? old.stones.map((stone) => normalizeStone(stone as Partial<Stone>)) : [newStone()]; const legacyStarter = typeof old.starterAction === "string" ? old.starterAction : ""; const next = stones.find((stone) => !stone.done); if (legacyStarter && next && !next.starterAction) next.starterAction = legacyStarter; const bigStone: BigStone = { id: uid(), title: typeof old.bigStone === "string" ? old.bigStone : "", finishLine: typeof old.finishLine === "string" ? old.finishLine : "", stones }; if (isBigStoneComplete(bigStone)) { bigStone.completedAt = `${key}T23:59:59`; completedBigStoneIds.push(bigStone.id); } return [key, { bigStones: [bigStone], freeStones: Array.isArray(old.freeStones) ? old.freeStones.map((stone) => normalizeStone(stone as Partial<Stone>)) : [] }]; }));
  return { version: 2, days, unlocks: { completedBigStoneIds, twoStoneDays: [], second: completedBigStoneIds.length >= 7, third: false } };
}

const compressImage = (file: File) => new Promise<string>((resolve, reject) => { const source = URL.createObjectURL(file); const image = new Image(); image.onload = () => { const maxEdge = 1280; const scale = Math.min(1, maxEdge / Math.max(image.naturalWidth, image.naturalHeight)); const canvas = document.createElement("canvas"); canvas.width = Math.max(1, Math.round(image.naturalWidth * scale)); canvas.height = Math.max(1, Math.round(image.naturalHeight * scale)); const context = canvas.getContext("2d"); if (!context) { URL.revokeObjectURL(source); reject(new Error("canvas unavailable")); return; } context.fillStyle = "#fff"; context.fillRect(0, 0, canvas.width, canvas.height); context.drawImage(image, 0, 0, canvas.width, canvas.height); URL.revokeObjectURL(source); resolve(canvas.toDataURL("image/webp", 0.76)); }; image.onerror = () => { URL.revokeObjectURL(source); reject(new Error("image decode failed")); }; image.src = source; });

function StarRating({ value, onChange, label }: { value: number; onChange: (value: number) => void; label: string }) { return <div className="rating-row"><span>{label}</span><div className="stars" role="radiogroup" aria-label={`${label}评分`}>{[1, 2, 3, 4, 5].map((score) => <button key={score} type="button" className={score <= value ? "star active" : "star"} onClick={() => onChange(score === value ? 0 : score)} aria-label={`${score}星`} aria-checked={score === value} role="radio"><Star aria-hidden="true" /></button>)}</div></div>; }

function ReviewPanel({ stone, onReview }: { stone: Stone; onReview: (patch: Partial<Review>) => void }) {
  const fileRef = useRef<HTMLInputElement>(null);
  const handleFile = async (file?: File) => { if (!file?.type.startsWith("image/")) return; try { onReview({ image: await compressImage(file) }); } catch { /* keep current image */ } if (fileRef.current) fileRef.current.value = ""; };
  return <div className="review-panel" onClick={(event) => event.stopPropagation()}><div className="review-title"><div><span className="eyebrow">可选记录</span><strong>想记下这次的感受吗？</strong></div><span className="earned">+{stone.weight} 石头值</span></div><StarRating label="投入程度" value={stone.review.effort} onChange={(effort) => onReview({ effort })} /><StarRating label="成就感" value={stone.review.achievement} onChange={(achievement) => onReview({ achievement })} /><textarea value={stone.review.note} onChange={(event) => onReview({ note: event.target.value })} placeholder="写下一句话，留给以后的自己…" aria-label="文字记录" /><input ref={fileRef} type="file" accept="image/*" className="sr-only" onChange={(event) => void handleFile(event.target.files?.[0])} />{stone.review.image ? <div className="image-preview"><img src={stone.review.image} alt="阶段成果预览" /><button type="button" onClick={() => onReview({ image: undefined })} aria-label="移除图片"><X /></button></div> : <button className="upload-button" type="button" onClick={() => fileRef.current?.click()}><ImagePlus /> 上传照片 / 截图</button>}</div>;
}

function StoneRow({ stone, index, kind, isNext, expanded, onExpand, onPatch, onDelete, onComplete }: { stone: Stone; index: number; kind: "big" | "free"; isNext?: boolean; expanded: boolean; onExpand: () => void; onPatch: (patch: Partial<Stone>) => void; onDelete: () => void; onComplete: (checked: boolean) => void }) {
  return <article className={`stone-row ${stone.done ? "is-done" : ""} ${isNext ? "is-next" : ""}`}><div className="stone-main"><div className="stone-check"><Checkbox checked={stone.done} onCheckedChange={(checked) => onComplete(Boolean(checked))} aria-label={`${stone.action || `第${index + 1}块小石头`}完成`} /><span>{index + 1}</span></div><div className="stone-fields"><input className="action-input" value={stone.action} onChange={(event) => onPatch({ action: event.target.value })} placeholder={kind === "big" ? "要完成的动作" : "记录一件有意义的事"} aria-label="动作" />{kind === "big" && <input value={stone.outcome} onChange={(event) => onPatch({ outcome: event.target.value })} placeholder="阶段成果（例如：一份可录制脚本）" aria-label="阶段成果" />}</div><div className="weight-picker"><div className="weight-stepper" role="group" aria-label="石头重量"><button type="button" onClick={() => onPatch({ weight: stone.weight - 1 })} disabled={stone.weight <= 1} aria-label="减轻重量"><Minus /></button><output aria-label={`当前重量 ${stone.weight}`}>{stone.weight}</output><button type="button" onClick={() => onPatch({ weight: stone.weight + 1 })} disabled={stone.weight >= 5} aria-label="增加重量"><Plus /></button></div></div><div className="stone-actions">{stone.done && <button className="icon-button review-toggle" type="button" onClick={onExpand} aria-label="展开评价"><ChevronDown className={expanded ? "rotate" : ""} /></button>}<button className="icon-button delete" type="button" onClick={onDelete} aria-label="删除小石头"><Trash2 /></button></div></div>{isNext && !stone.done && <span className="next-label">下一块</span>}{isNext && !stone.done && <div className="starter-card"><span className="starter-icon"><GripVertical /></span><strong>现在先做什么？</strong><input value={stone.starterAction} onChange={(event) => onPatch({ starterAction: event.target.value })} placeholder="例如：打开文档，先写第一句话" aria-label={`第${index + 1}块小石头现在先做什么`} /></div>}{expanded && stone.done && <ReviewPanel stone={stone} onReview={(review) => onPatch({ review: { ...stone.review, ...review } })} />}</article>;
}

function BigStoneEditor({ big, index, history, expanded, onExpanded, onPatch, onStonePatch, onStoneDelete, onStoneComplete, onAddStone, onCheck, onDelete }: { big: BigStone; index: number; history: string[]; expanded: string | null; onExpanded: (id: string | null) => void; onPatch: (patch: Partial<BigStone>) => void; onStonePatch: (id: string, patch: Partial<Stone>) => void; onStoneDelete: (id: string) => void; onStoneComplete: (stone: Stone, checked: boolean) => void; onAddStone: () => void; onCheck: () => void; onDelete?: () => void }) {
  const total = big.stones.reduce((sum, stone) => sum + stone.weight, 0); const completed = big.stones.filter((stone) => stone.done).reduce((sum, stone) => sum + stone.weight, 0); const progress = total ? Math.round(completed / total * 100) : 0; const next = big.stones.find((stone) => !stone.done); const headings = ["今天最重要的大石头是什么？", "今天还想推进的一块石头", "今天还想推进的第三块石头"];
  return <section className={`big-stone-section ${index > 0 ? "secondary-big" : ""}`}><div className="section-heading"><div><span className="step-number">{`01${String.fromCharCode(65 + index)}`}</span><h1>{headings[index]}</h1></div><div className="heading-actions">{big.completedAt && <span className="complete-chip"><Check /> 已完成</span>}{index === 0 ? <span className="autosave"><Check /> 已保存在本机</span> : onDelete && <button className="remove-big" type="button" onClick={onDelete}><Trash2 /> 删除</button>}</div></div><div className="big-stone-card"><input className="big-stone-input" value={big.title} onChange={(event) => onPatch({ title: event.target.value })} placeholder={index === 0 ? "例如：完成并发布一条 AI 视频" : "写下另一件真正值得推进的事"} aria-label={`第${index + 1}块大石头`} />{history.length > 0 && <div className="history-row"><span>最近写过</span>{history.map((item) => <button type="button" key={item} onClick={() => onPatch({ title: item })}>{item}</button>)}</div>}<div className="finish-line"><span>做到什么程度，算完成？</span><input value={big.finishLine} onChange={(event) => onPatch({ finishLine: event.target.value })} placeholder="写下一个看得见、能验证的结果" aria-label="完成标准" /></div><div className="big-progress"><div className="progress-copy"><div><span>大石头进度</span><strong>{completed}<small> / {total || 0}</small></strong></div><span>{progress === 100 && total > 0 ? "已经放进去了" : progress > 0 ? "正在推进" : "还没有开始搬"}</span></div><Progress value={progress} aria-label={`大石头进度 ${progress}%`} /></div></div><div className="section-heading compact"><div><span className="step-number">02</span><h2>把它拆成能动手的小石头</h2></div><button type="button" className="ai-placeholder" onClick={onCheck}><Sparkles /> 帮我检查拆分</button></div><div className="stone-table-labels" aria-hidden="true"><span>序号</span><span>动作 / 阶段成果</span><span>重量 1–5</span><span /></div><div className="mobile-weight-hint">重量 1–5</div><div className="stone-list" onClick={(event) => event.stopPropagation()}>{big.stones.map((stone, stoneIndex) => <StoneRow key={stone.id} stone={stone} index={stoneIndex} kind="big" isNext={stone.id === next?.id} expanded={expanded === stone.id} onExpand={() => onExpanded(expanded === stone.id ? null : stone.id)} onPatch={(patch) => onStonePatch(stone.id, patch)} onDelete={() => onStoneDelete(stone.id)} onComplete={(checked) => onStoneComplete(stone, checked)} />)}</div><button className="add-button" type="button" onClick={onAddStone}><CirclePlus /> 添加一块小石头</button></section>;
}

function WaterJar({ stones, splashing = false }: { stones: Array<Stone & { kind?: "big" | "free" }>; splashing?: boolean }) { return <div className={`water-jar ${splashing ? "is-splashing" : ""}`} aria-label="今日完成石头可视化"><div className="jar-water"><span className="water-surface" /></div><span className="spill spill-left" /><span className="spill spill-right" /><div className="jar-pebbles">{stones.slice(-12).map((stone, index) => <i key={stone.id} className={stone.kind === "free" ? "free-pebble" : ""} style={{ "--size": stone.weight, "--i": index } as React.CSSProperties} />)}</div><div className="jar-rim" /></div>; }

export default function Home() {
  const [selectedDate, setSelectedDate] = useState(todayKey()); const [data, setData] = useState<AppData>(emptyData()); const [hydrated, setHydrated] = useState(false); const [view, setView] = useState<View>("today"); const [expanded, setExpanded] = useState<string | null>(null); const [notice, setNotice] = useState(""); const [celebration, setCelebration] = useState<Celebration | null>(null); const [pendingImport, setPendingImport] = useState<{ name: string; value: AppData } | null>(null); const importRef = useRef<HTMLInputElement>(null);
  const day = data.days[selectedDate] ?? emptyDay(); const maxBigStones = allowedBigStones(data.unlocks);
  const titleHistory = useMemo(() => unique(Object.values(data.days).flatMap((saved) => saved.bigStones.map((stone) => stone.title.trim())).filter(Boolean)).slice(-8).reverse(), [data.days]);
  const completedVisualStones = [...day.bigStones.flatMap((big) => big.stones.filter((stone) => stone.done).map((stone) => ({ ...stone, kind: "big" as const }))), ...day.freeStones.filter((stone) => stone.done).map((stone) => ({ ...stone, kind: "free" as const }))];
  const bigWeights = day.bigStones.map((big) => ({ total: big.stones.reduce((sum, stone) => sum + stone.weight, 0), done: big.stones.filter((stone) => stone.done).reduce((sum, stone) => sum + stone.weight, 0) })); const totalBigWeight = bigWeights.reduce((sum, value) => sum + value.total, 0); const completedBigWeight = bigWeights.reduce((sum, value) => sum + value.done, 0); const freeWeight = day.freeStones.filter((stone) => stone.done).reduce((sum, stone) => sum + stone.weight, 0);

  useEffect(() => { try { const saved = localStorage.getItem(STORAGE_KEY); const legacy = localStorage.getItem(LEGACY_KEY); if (saved) setData(normalizeData(JSON.parse(saved))); else if (legacy) setData(normalizeData(JSON.parse(legacy))); } catch { setNotice("本机记录读取失败，请检查浏览器存储权限。"); } finally { setHydrated(true); } }, []);
  useEffect(() => { if (!hydrated) return; try { localStorage.setItem(STORAGE_KEY, JSON.stringify(data)); } catch { setNotice("照片可能过大，本次修改暂时无法保存。"); } }, [data, hydrated]);
  useEffect(() => { if ("serviceWorker" in navigator) void navigator.serviceWorker.register("/sw.js"); }, []);
  const updateDay = (updater: (current: DayData) => DayData) => setData((current) => ({ ...current, days: { ...current.days, [selectedDate]: updater(current.days[selectedDate] ?? emptyDay()) } }));
  const updateBig = (bigId: string, patch: Partial<BigStone>) => updateDay((current) => ({ ...current, bigStones: current.bigStones.map((big) => big.id === bigId ? { ...big, ...patch } : big) }));
  const updateStone = (bigId: string, stoneId: string, patch: Partial<Stone>) => updateDay((current) => ({ ...current, bigStones: current.bigStones.map((big) => big.id === bigId ? { ...big, stones: big.stones.map((stone) => stone.id === stoneId ? { ...stone, ...patch } : stone) } : big) }));
  const updateFreeStone = (stoneId: string, patch: Partial<Stone>) => updateDay((current) => ({ ...current, freeStones: current.freeStones.map((stone) => stone.id === stoneId ? { ...stone, ...patch } : stone) }));
  const showCelebration = (kind: Celebration["kind"], weight: number) => { setCelebration({ kind, weight }); window.setTimeout(() => setCelebration(null), kind === "small" ? 1400 : 2600); };

  const completeBigStoneStep = (big: BigStone, stone: Stone, checked: boolean) => {
    const patchedStones = big.stones.map((item) => item.id === stone.id ? { ...item, done: checked } : item); const newlyCompleted = checked && !big.completedAt && isBigStoneComplete({ ...big, stones: patchedStones }); const completedIdsAfter = unique([...data.unlocks.completedBigStoneIds, ...(newlyCompleted ? [big.id] : [])]); const completedTodayAfter = day.bigStones.filter((item) => item.id === big.id ? newlyCompleted || Boolean(item.completedAt) : Boolean(item.completedAt)).length; const addsTwoStoneDay = newlyCompleted && completedTodayAfter >= 2 && !data.unlocks.twoStoneDays.includes(selectedDate); const twoStoneDaysAfter = unique([...data.unlocks.twoStoneDays, ...(addsTwoStoneDay ? [selectedDate] : [])]); const unlockSecond = !data.unlocks.second && completedIdsAfter.length >= 7; const unlockThird = !data.unlocks.third && twoStoneDaysAfter.length >= 5;
    setData((current) => { const currentDay = current.days[selectedDate] ?? emptyDay(); return { ...current, days: { ...current.days, [selectedDate]: { ...currentDay, bigStones: currentDay.bigStones.map((item) => item.id === big.id ? { ...item, stones: item.stones.map((entry) => entry.id === stone.id ? { ...entry, done: checked } : entry), completedAt: newlyCompleted ? new Date().toISOString() : item.completedAt } : item) } }, unlocks: { completedBigStoneIds: completedIdsAfter, twoStoneDays: twoStoneDaysAfter, second: current.unlocks.second || unlockSecond, third: current.unlocks.third || unlockThird } }; });
    if (!checked) { setExpanded(null); return; } setExpanded(stone.id); showCelebration(unlockThird ? "third" : unlockSecond ? "second" : newlyCompleted ? "big" : "small", stone.weight);
  };
  const completeFreeStone = (stone: Stone, checked: boolean) => { updateFreeStone(stone.id, { done: checked }); if (!checked) { setExpanded(null); return; } setExpanded(stone.id); showCelebration("small", stone.weight); };
  const checkBreakdown = (big: BigStone) => { const issues: string[] = []; if (!big.title.trim()) issues.push("先写下这块大石头"); if (!big.finishLine.trim()) issues.push("补充明确的完成标准"); if (big.stones.some((stone) => !stone.action.trim())) issues.push("有小石头还没有动作"); if (big.stones.some((stone) => !stone.outcome.trim())) issues.push("有阶段成果还没写清楚"); setNotice(issues.length ? `占位检查：${issues.join("；")}。` : "占位检查：拆分已经很清楚。真实 AI 检查将在后续版本接入。"); };

  useEffect(() => {
    const modelContext = (document as Document & { modelContext?: { registerTool: (tool: unknown, options?: { signal?: AbortSignal }) => void | Promise<void> } }).modelContext;
    if (!modelContext?.registerTool) return;
    const lifecycle = new AbortController();
    try { void Promise.resolve(modelContext.registerTool({
      name: "add_small_stone", title: "添加小石头", description: "为当前日期的大石头添加一个行动步骤。",
      inputSchema: { type: "object", properties: { action: { type: "string" }, weight: { type: "integer", minimum: 1, maximum: 5 }, outcome: { type: "string" }, big_stone_number: { type: "integer", minimum: 1, maximum: 3 } }, required: ["action", "weight"], additionalProperties: false },
      annotations: { readOnlyHint: false, untrustedContentHint: false },
      execute: (input: unknown) => { const value = input as { action?: unknown; weight?: unknown; outcome?: unknown; big_stone_number?: unknown }; if (typeof value.action !== "string" || !value.action.trim() || !Number.isInteger(value.weight) || Number(value.weight) < 1 || Number(value.weight) > 5) throw new Error("请提供动作和 1–5 的重量"); const number = Math.max(1, Math.min(3, Number(value.big_stone_number) || 1)); const stone = newStone({ action: value.action.trim(), weight: Number(value.weight), outcome: typeof value.outcome === "string" ? value.outcome : "" }); updateDay((current) => ({ ...current, bigStones: current.bigStones.map((big, index) => index === number - 1 ? { ...big, stones: [...big.stones, stone] } : big) })); return { id: stone.id, added: true, big_stone_number: number }; },
    }, { signal: lifecycle.signal })).catch(() => undefined); } catch { /* unsupported preview context */ }
    return () => lifecycle.abort();
  }, [selectedDate]);

  const exportData = () => { const exported = { ...data, lastExportAt: new Date().toISOString() }; const blob = new Blob([JSON.stringify(exported, null, 2)], { type: "application/json" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `move-one-stone-backup-${todayKey()}.json`; anchor.click(); URL.revokeObjectURL(url); setData(exported); setNotice("备份文件已经导出。"); };
  const readImport = async (file?: File) => { if (!file) return; try { const value = normalizeData(JSON.parse(await file.text())); setPendingImport({ name: file.name, value }); } catch { setNotice("无法识别这个文件，请选择石头记导出的 JSON 备份。"); } if (importRef.current) importRef.current.value = ""; };
  const applyImport = (mode: "overwrite" | "merge") => { if (!pendingImport) return; if (mode === "overwrite") setData(pendingImport.value); else setData((current) => { const mergedDays = { ...pendingImport.value.days }; Object.entries(current.days).forEach(([key, local]) => { const incoming = mergedDays[key]; if (!incoming) { mergedDays[key] = local; return; } mergedDays[key] = { bigStones: [...local.bigStones, ...incoming.bigStones.filter((stone) => !local.bigStones.some((item) => item.id === stone.id))], freeStones: [...local.freeStones, ...incoming.freeStones.filter((stone) => !local.freeStones.some((item) => item.id === stone.id))] }; }); return { version: 2, days: mergedDays, unlocks: { completedBigStoneIds: unique([...current.unlocks.completedBigStoneIds, ...pendingImport.value.unlocks.completedBigStoneIds]), twoStoneDays: unique([...current.unlocks.twoStoneDays, ...pendingImport.value.unlocks.twoStoneDays]), second: current.unlocks.second || pendingImport.value.unlocks.second, third: current.unlocks.third || pendingImport.value.unlocks.third }, lastExportAt: current.lastExportAt }; }); setNotice(`已${mode === "overwrite" ? "覆盖" : "合并"} ${Object.keys(pendingImport.value.days).length} 天记录。`); setPendingImport(null); };
  const clearData = () => { if (!window.confirm("确定清空这台设备上的全部记录吗？导出备份后再清空会更安全。")) return; localStorage.removeItem(STORAGE_KEY); localStorage.removeItem(LEGACY_KEY); setData(emptyData()); setNotice("本机记录已经清空。"); };
  const historyDays = Object.entries(data.days).filter(([, saved]) => saved.bigStones.some((big) => big.title.trim()) || saved.freeStones.length).sort(([a], [b]) => b.localeCompare(a));

  if (!hydrated) return <main className="loading-screen">正在搬来今天的石头…</main>;
  return <main className="app-shell" onClick={() => expanded && setExpanded(null)}><div className="ambient ambient-one" /><div className="ambient ambient-two" />
    <header className="topbar"><button className="brand" type="button" onClick={() => setView("today")} aria-label="回到石头记今日页"><span className="brand-mark"><Mountain /></span><span className="brand-copy"><strong>石头记</strong><em>Move One Stone</em></span></button><nav className="main-nav" aria-label="主要功能"><button className={view === "today" ? "active" : ""} onClick={() => setView("today")}><Mountain />今日</button><button className={view === "history" ? "active" : ""} onClick={() => setView("history")}><History />历史</button><button className={view === "data" ? "active" : ""} onClick={() => setView("data")}><Database />数据</button></nav>{view === "today" && <div className="date-nav"><button type="button" onClick={() => setSelectedDate(shiftDate(selectedDate, -1))} aria-label="前一天"><ChevronLeft /></button><label><CalendarDays /><span>{displayDate(selectedDate)}</span><input type="date" value={selectedDate} max={todayKey()} onChange={(event) => setSelectedDate(event.target.value)} aria-label="选择日期" /></label><button type="button" disabled={selectedDate >= todayKey()} onClick={() => setSelectedDate(shiftDate(selectedDate, 1))} aria-label="后一天"><ChevronRight /></button></div>}</header>
    {view === "today" && <div className="page-grid"><section className="workspace">{day.bigStones.map((big, index) => <BigStoneEditor key={big.id} big={big} index={index} history={titleHistory} expanded={expanded} onExpanded={setExpanded} onPatch={(patch) => updateBig(big.id, patch)} onStonePatch={(stoneId, patch) => updateStone(big.id, stoneId, patch)} onStoneDelete={(stoneId) => updateBig(big.id, { stones: big.stones.filter((stone) => stone.id !== stoneId) })} onStoneComplete={(stone, checked) => completeBigStoneStep(big, stone, checked)} onAddStone={() => updateBig(big.id, { stones: [...big.stones, newStone()] })} onCheck={() => checkBreakdown(big)} onDelete={index > 0 ? () => updateDay((current) => ({ ...current, bigStones: current.bigStones.filter((item) => item.id !== big.id) })) : undefined} />)}{day.bigStones.length < maxBigStones && <button className="add-big-button" type="button" onClick={() => updateDay((current) => ({ ...current, bigStones: [...current.bigStones, newBigStone()] }))}><CirclePlus /> {day.bigStones.length === 1 ? "添加今天的第二块大石头" : "添加今天的第三块大石头"}</button>}{!data.unlocks.second && <div className="unlock-progress"><strong>第二块大石头</strong><span>再完成 {Math.max(0, 7 - data.unlocks.completedBigStoneIds.length)} 个大石头后永久解锁</span><Progress value={Math.min(100, data.unlocks.completedBigStoneIds.length / 7 * 100)} /></div>}{data.unlocks.second && !data.unlocks.third && <div className="unlock-progress"><strong>第三块大石头</strong><span>累计 {data.unlocks.twoStoneDays.length}/5 天完成两块大石头</span><Progress value={Math.min(100, data.unlocks.twoStoneDays.length / 5 * 100)} /></div>}
      <section className="free-section"><div className="section-heading compact"><div><span className="step-number mint">03</span><div><h2>今日自由小石头</h2><p>记录计划之外、但同样有意义的事</p></div></div></div><div className="stone-list free-list" onClick={(event) => event.stopPropagation()}>{day.freeStones.length === 0 && <button className="empty-free" type="button" onClick={() => updateDay((current) => ({ ...current, freeStones: [...current.freeStones, newStone()] }))}><span><Plus /></span><strong>记录第一块自由小石头</strong><small>健身、读书、主动沟通……都值得被看见</small></button>}{day.freeStones.map((stone, index) => <StoneRow key={stone.id} stone={stone} index={index} kind="free" expanded={expanded === stone.id} onExpand={() => setExpanded(expanded === stone.id ? null : stone.id)} onPatch={(patch) => updateFreeStone(stone.id, patch)} onDelete={() => updateDay((current) => ({ ...current, freeStones: current.freeStones.filter((item) => item.id !== stone.id) }))} onComplete={(checked) => completeFreeStone(stone, checked)} />)}</div>{day.freeStones.length > 0 && <button className="add-button subtle" type="button" onClick={() => updateDay((current) => ({ ...current, freeStones: [...current.freeStones, newStone()] }))}><Plus /> 记录一块自由小石头</button>}</section>
    </section><aside className="today-summary"><span className="summary-kicker">TODAY</span><h2>今天留下了多少推进？</h2><div className="summary-hero"><span>大石头总进度</span><strong>{completedBigWeight}<small> / {totalBigWeight || 0}</small></strong><Progress value={totalBigWeight ? completedBigWeight / totalBigWeight * 100 : 0} /><p>记录的不是忙碌，而是生活真正向前的部分。</p></div><div className="summary-stats"><div><span>今日总石头值</span><strong>{completedBigWeight + freeWeight}</strong></div><div><span>完成大石头</span><strong>{day.bigStones.filter((big) => big.completedAt).length}<small> 块</small></strong></div><div><span>自由小石头</span><strong>{freeWeight}</strong></div></div><WaterJar stones={completedVisualStones} splashing={Boolean(celebration)} /><p className="summary-note">水会自然流进一天，重要的石头需要主动放进去。</p></aside></div>}
    {view === "history" && <section className="secondary-page"><div className="page-title"><span>HISTORY</span><h1>过去真正推进了什么</h1><p>按日期回看大石头、小石头、启动动作和记录。</p></div>{historyDays.length === 0 ? <div className="empty-page"><History /><strong>还没有历史记录</strong><span>完成今天的第一块石头后，它会出现在这里。</span></div> : <div className="history-grid">{historyDays.map(([key, saved]) => { const dayValue = saved.bigStones.flatMap((big) => big.stones).filter((stone) => stone.done).reduce((sum, stone) => sum + stone.weight, 0) + saved.freeStones.filter((stone) => stone.done).reduce((sum, stone) => sum + stone.weight, 0); return <article className="history-card" key={key}><div className="history-card-head"><div><span>{displayDate(key)}</span><strong>{dayValue} 石头值</strong></div><button onClick={() => { setSelectedDate(key); setView("today"); }}>打开当天</button></div>{saved.bigStones.map((big, index) => <div className="history-big" key={big.id}><span>大石头 {index + 1}{big.completedAt ? " · 已完成" : ""}</span><h2>{big.title || "未命名的大石头"}</h2>{big.finishLine && <p>完成标准：{big.finishLine}</p>}<ul>{big.stones.filter((stone) => stone.action.trim()).map((stone) => <li key={stone.id} className={stone.done ? "done" : ""}><Check /><div><strong>{stone.action}</strong>{stone.starterAction && <small>第一步：{stone.starterAction}</small>}</div><span>{stone.weight}</span></li>)}</ul></div>)}{saved.freeStones.length > 0 && <div className="history-free"><span>自由小石头</span>{saved.freeStones.map((stone) => <em key={stone.id}>{stone.action || "未命名"}</em>)}</div>}</article>; })}</div>}</section>}
    {view === "data" && <section className="secondary-page data-page"><div className="page-title"><span>YOUR DATA</span><h1>备份与迁移</h1><p>数据仍只保存在当前设备。导出文件后，可以在另一台设备上导入。</p></div><div className="data-overview"><div><strong>{Object.keys(data.days).length}</strong><span>有记录的日期</span></div><div><strong>{data.unlocks.completedBigStoneIds.length}</strong><span>累计完成大石头</span></div><div><strong>{data.unlocks.twoStoneDays.length}</strong><span>完成双石的日期</span></div></div><div className="data-actions"><article><Download /><div><strong>导出全部数据</strong><span>{data.lastExportAt ? `上次导出：${new Date(data.lastExportAt).toLocaleString("zh-CN")}` : "还没有导出过备份"}</span></div><button onClick={exportData}>导出 JSON</button></article><article><Upload /><div><strong>从备份文件导入</strong><span>可以覆盖当前数据，也可以与当前记录合并。</span></div><input ref={importRef} className="sr-only" type="file" accept="application/json,.json" onChange={(event) => void readImport(event.target.files?.[0])} /><button onClick={() => importRef.current?.click()}>选择文件</button></article><article className="danger-action"><RotateCcw /><div><strong>清空本机数据</strong><span>此操作不可撤销，建议先导出备份。</span></div><button onClick={clearData}>清空</button></article></div>{pendingImport && <div className="import-confirm"><div><strong>已读取 {pendingImport.name}</strong><span>包含 {Object.keys(pendingImport.value.days).length} 天记录。请选择导入方式。</span></div><button onClick={() => applyImport("merge")}>与当前数据合并</button><button className="overwrite" onClick={() => applyImport("overwrite")}>覆盖当前数据</button><button className="cancel" onClick={() => setPendingImport(null)}>取消</button></div>}<p className="privacy-note">照片会包含在备份文件中，因此文件可能较大。请把备份保存在你信任的位置。</p></section>}
    {notice && <div className="notice" role="status"><Sparkles /><span>{notice}</span><button type="button" onClick={() => setNotice("")} aria-label="关闭"><X /></button></div>}
    {celebration && <div className={`celebration ${celebration.kind}`} role="status" aria-live="polite"><div className="splash-scene"><span className="scene-spill scene-left" /><span className="scene-spill scene-right" /><div className="scene-water" /><i className="splash-stone" style={{ "--size": celebration.weight } as React.CSSProperties} /><div className="scene-rim" /></div><strong>{celebration.kind === "second" ? "第二块大石头，解锁了。" : celebration.kind === "third" ? "第三块大石头，解锁了。" : celebration.kind === "big" ? "今天的大石头，放进去了。" : "咚！又放进了一块。"}</strong><span>{celebration.kind === "second" ? "完成 7 个大石头后永久解锁" : celebration.kind === "third" ? "你已经积累了 5 个双石日" : `+${celebration.weight} 石头值，水被挤出了一点`}</span></div>}
  </main>;
}
